controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    prbt_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


prbt_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - prbt_joint_1
      - prbt_joint_2
      - prbt_joint_3
      - prbt_joint_4
      - prbt_joint_5
      - prbt_joint_6
