controller_names:
  - prbt_arm_controller

prbt_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - prbt_joint_1
    - prbt_joint_2
    - prbt_joint_3
    - prbt_joint_4
    - prbt_joint_5
    - prbt_joint_6
