amcl:
  ros__parameters:
    use_sim_time: True  # 使用仿真时间
    alpha1: 0.2  # AMCL 的运动模型参数
    alpha2: 0.2  # AMCL 的运动模型参数
    alpha3: 0.2  # AMCL 的运动模型参数
    alpha4: 0.2  # AMCL 的运动模型参数
    alpha5: 0.2  # AMCL 的运动模型参数
    base_frame_id: "base_footprint"  # 机器人底部坐标系的 ID
    beam_skip_distance: 0.5  # 光束跳跃的距离
    beam_skip_error_threshold: 0.9  # 光束跳跃误差阈值
    beam_skip_threshold: 0.3  # 光束跳跃阈值
    do_beamskip: false  # 是否执行光束跳跃
    global_frame_id: "map"  # 全局地图坐标系的 ID
    lambda_short: 0.1  # 短测量的衰减因子
    laser_likelihood_max_dist: 2.0  # 激光传感器可能性模型的最大距离
    laser_max_range: 64.0   # 激光传感器的最大测量距离    100 
    laser_min_range: 0.01  # 激光传感器的最小测量距离
    laser_model_type: "likelihood_field"  # 激光传感器模型类型
    max_beams: 60  # 最大光束数
    max_particles: 2000  # 粒子滤波器的最大粒子数  2000
    min_particles: 500  # 粒子滤波器的最小粒子数  500
    odom_frame_id: "odom"  # 里程计坐标系的 ID
    pf_err: 0.05  # 粒子滤波器的误差  0.05
    pf_z: 0.99  # 粒子滤波器的重采样阈值
    recovery_alpha_fast: 0.0  # 快速恢复的衰减因子
    recovery_alpha_slow: 0.0  # 慢速恢复的衰减因子
    resample_interval: 1  # 重采样间隔
    robot_model_type: "nav2_amcl::DifferentialMotionModel"  # 机器人运动模型类型
    save_pose_rate: 0.5  # 保存姿态的频率
    sigma_hit: 0.2  # 命中模型的标准差
    tf_broadcast: true  # 是否广播 TF
    transform_tolerance: 1.0  # 坐标变换的容忍度
    update_min_a: 0.2  # 更新运动的最小角度  0.2
    update_min_d: 0.25  # 更新运动的最小距离  0.25 
    z_hit: 0.5  # 命中的权重
    z_max: 0.05  # 最大测量距离的权重
    z_rand: 0.5  # 随机测量的权重
    z_short: 0.05  # 短测量的权重
    scan_topic: scan  # 激光扫描主题
    set_initial_pose: true #true
    always_reset_initial_pose: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 1.0


bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_footprint #base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 15.0 # 20
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.05 # 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      
      required_movement_radius: 0.2
      movement_time_allowance: 15.0 # 10.0

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.13 # 0.25
      yaw_goal_tolerance: 0.10 # 0.25

    # DWB parameters
    # 设置跟随路径局部规划器参数
    FollowPath:
      # 使用dwb_core::DWBLocalPlanner插件进行路径跟随
      plugin: "dwb_core::DWBLocalPlanner"

      # # 添加旋转微调器
      # plugin: "nav2_rotation_shim_controller::RotationShimController"
      # primary_controller: "dwb_core::DWBLocalPlanner"
      # angular_dist_threshold: 0.785
      # forward_sampling_distance: 0.2
      # rotate_to_heading_angular_vel: 0.6 #1.8
      # max_angular_accel: 0.3 #3.2
      # simulate_ahead_time: 1.0

      
      debug_trajectory_details: True # 是否调试轨迹详情      
      min_vel_x: 0.0 # 最小线速度（x方向）     
      min_vel_y: 0.0 # 最小线速度（y方向）,差分驱动设置为0  
      max_vel_x: 0.26 # 最大线速度（x方向） 
      max_vel_y: 0.0 # 最大线速度（y方向）,差分驱动设置为0 
      max_vel_theta: 0.6 # 最大角速度 0.3
      min_vel_theta: -0.6 # 最小角速度 0.3
      min_speed_xy: 0.0 # 最小速度（线性）
      max_speed_xy: 0.26  # 最大速度（线性） 0.26
      min_speed_theta: -0.5 # 最小速度（角度） 0.0
      max_speed_theta: 0.5 # 最大速度（角度） 0.4
      acc_lim_x: 2.0 # x轴加速度限制 2.5
      acc_lim_y: 0.0 # y轴加速度限制
      acc_lim_theta: 0.2 # 角速度加速度限制 3.2
      decel_lim_x: -2.5 # x轴减速度限制
      decel_lim_y: 0.0 # y轴减速度限制
      decel_lim_theta: -0.2 # 角速度减速度限制 -3.2
      vx_samples: 10 # x轴速度样本数 20
      vy_samples: 1 # y轴速度样本数 5
      vtheta_samples: 10  # 角速度样本数 2 0
      sim_time: 4.0 # 仿真时间 1.7
      linear_granularity: 0.05 # 线性分辨率
      angular_granularity: 0.025 # 角度分辨率
      transform_tolerance: 0.03 # 变换容差 0.2
      xy_goal_tolerance: 0.03 # XY目标容差 0.25
      trans_stopped_velocity: 0.01 # 停止转换速度
      short_circuit_trajectory_evaluation: True # 是否启用轨迹评估的快速通道
      stateful: True # 是否状态化

      # 所使用的评价器 "BaseObstacle",
      critics: ["RotateToGoal", "Oscillation",  "BaseObstacle","GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.off_grid_scale: 0.08
      #########  振荡评价器   ###########
      Oscillation.scale: 3.0

      # BaseObstacle.scale: 1.0 # 0.02 # # 基础障碍物评价器的权重
      #########  路径对齐评价器   ###########
      PathAlign.scale: 0.0 # 路径对齐评价器的权重 32.0 
      PathAlign.forward_point_distance: 0.1  # 路径对齐评价器的前向点距离 0.1

      #########  目标对齐评价器   ###########
      GoalAlign.scale: 0.0 # 24.0 # 目标对齐评价器的权重
      GoalAlign.forward_point_distance: 0.2 # 目标对齐评价器的前向点距离 0.1

      #########  路径距离评价器   ########### 
      PathDist.scale: 40.0 # 路径距离评价器的权重 32.0

      #########  目标距离评价器   ###########
      GoalDist.scale: 45.0 # 目标距离评价器的权重 32.0

      #########  旋转至目标评价器   ###########
      RotateToGoal.scale: 40.0 # 旋转至目标评价器的权重 32.0  
      RotateToGoal.slowing_factor: 5.0 # 旋转至目标评价器的减速因子 5.0      
      RotateToGoal.lookahead_time: -1.0 # 旋转至目标评价器的预测时间 -1.0

      

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link #base_link base_footprint
      use_sim_time: True
      rolling_window: true
      width: 3 #3
      height: 3 #3
      resolution: 0.05
      # robot_radius: 0.22
      footprint: "[ [0.352, 0.270], [0.352, -0.270], [-0.352, -0.270], [-0.352, 0.270] ]"

      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 0.5 # 3.0
        inflation_radius: 0.24 # 0.55
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0 #1.0
      publish_frequency: 2.0 #1.0
      global_frame: map
      robot_base_frame: base_link #base_link base_footprint
      use_sim_time: True
      robot_radius: 0.2 # 0.4
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0 # 3.0
        inflation_radius: 0.04 # 0.55
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: True
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    # expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      # 直线规划器
      plugin: "nav2_straightline_planner/StraightLine"
      interpolation_resolution: 0.1 # 0.1

      # 默认规划器
      # plugin: "nav2_navfn_planner/NavfnPlanner"
      # tolerance: 0.3 # 0.5
      # use_astar: true
      # allow_unknown: true

      # plugin: "nav2_theta_star_planner::ThetaStarPlanner" # In Iron and older versions, "/" was used instead of "::"
      # how_many_corners: 3
      # w_euc_cost: 1.0
      # w_traversal_cost: 2.0
      # w_heuristic_cost: 1.0

smoother_server:
  ros__parameters:
    use_sim_time: True
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin","backup", "drive_on_heading", "assisted_teleop", "wait"] #"backup", 
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_footprint #base_link
    transform_tolerance: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.4 # 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 0.2 #1.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    use_sim_time: True
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 0.1 # 20.0 
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.26, 0.0, 0.4] # [0.26, 0.0, 1.0]
    min_velocity: [-0.26, 0.0, -0.4] # [-0.26, 0.0, -1.0]
    max_accel: [0.2, 0.0, 0.2]   # [2.5, 0.0, 3.2]
    max_decel: [-0.2, 0.0, -0.2] # [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

