aubo_arm:
  #kinematics_solver: pick_ik/PickIkPlugin
  #kinematics_solver_timeout: 1.0
  #kinematics_solver_attempts: 3
  #mode: local
  #rotation_scale: 0.5
  #position_threshold: 50.0
  #orientation_threshold: 50.0
  #cost_threshold: 100000.0
  #minimal_displacement_weight: 0.0
  #gd_step_size: 0.001
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
