teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.8

    # old
    # enable_button: 2  # Left trigger button
    # enable_turbo_button: 5  # Right trigger button
    
    enable_button: 3  # Left trigger button
    enable_turbo_button: 7  # Right trigger button
